# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Language-Tea
version:      0.03
version_from: lib/Language/Tea.pm
installdirs:  site
requires:
    IPC::Open2:                    0
    Scalar::Util:                  0
    Symbol:                        0
    Test::More:                    0
    v6:                            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
